baseURL = "https://yosepjeon.github.io/"
languageCode = "ko-kr"
defaultContentLanguage = "ko"
theme = "terminal"
pagination.pagerSize = 5
buildFuture = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = "paraiso-dark"

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.ko]
    title = "Yosep's Blog"
    subtitle = "개발 블로그"
    keywords = ""
    copyright = ""
    menuMore = "더보기"
    readMore = "더 읽기"
    readOtherPosts = "다른 글 읽기"

    [languages.ko.params.logo]
      logoText = "Yosep's Tech 하이텔"
      logoHomeLink = "/"

    [languages.ko.menu]
      [[languages.ko.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1
      [[languages.ko.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 2
      [[languages.ko.menu.main]]
        identifier = "books"
        name = "Books"
        url = "/books"
        weight = 3